/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TecnologiaRouteImport } from './routes/tecnologia'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as SoftwareRouteImport } from './routes/software'
import { Route as RobloxRouteImport } from './routes/roblox'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ProgramacionRouteImport } from './routes/programacion'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as HelpRouteImport } from './routes/help'
import { Route as HardwareRouteImport } from './routes/hardware'
import { Route as GamedevRouteImport } from './routes/gamedev'
import { Route as ElectricidadRouteImport } from './routes/electricidad'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AiRouteImport } from './routes/ai'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as TemaCategorySlugRouteImport } from './routes/tema.$category.$slug'

const TecnologiaRoute = TecnologiaRouteImport.update({
  id: '/tecnologia',
  path: '/tecnologia',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const SoftwareRoute = SoftwareRouteImport.update({
  id: '/software',
  path: '/software',
  getParentRoute: () => rootRouteImport,
} as any)
const RobloxRoute = RobloxRouteImport.update({
  id: '/roblox',
  path: '/roblox',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramacionRoute = ProgramacionRouteImport.update({
  id: '/programacion',
  path: '/programacion',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const HardwareRoute = HardwareRouteImport.update({
  id: '/hardware',
  path: '/hardware',
  getParentRoute: () => rootRouteImport,
} as any)
const GamedevRoute = GamedevRouteImport.update({
  id: '/gamedev',
  path: '/gamedev',
  getParentRoute: () => rootRouteImport,
} as any)
const ElectricidadRoute = ElectricidadRouteImport.update({
  id: '/electricidad',
  path: '/electricidad',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const TemaCategorySlugRoute = TemaCategorySlugRouteImport.update({
  id: '/tema/$category/$slug',
  path: '/tema/$category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/ai': typeof AiRoute
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRoute
  '/electricidad': typeof ElectricidadRoute
  '/gamedev': typeof GamedevRoute
  '/hardware': typeof HardwareRoute
  '/help': typeof HelpRoute
  '/notifications': typeof NotificationsRoute
  '/premium': typeof PremiumRoute
  '/profile': typeof ProfileRoute
  '/programacion': typeof ProgramacionRoute
  '/projects': typeof ProjectsRoute
  '/roblox': typeof RobloxRoute
  '/software': typeof SoftwareRoute
  '/staff': typeof StaffRoute
  '/tecnologia': typeof TecnologiaRoute
  '/u/$username': typeof UUsernameRoute
  '/tema/$category/$slug': typeof TemaCategorySlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/ai': typeof AiRoute
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRoute
  '/electricidad': typeof ElectricidadRoute
  '/gamedev': typeof GamedevRoute
  '/hardware': typeof HardwareRoute
  '/help': typeof HelpRoute
  '/notifications': typeof NotificationsRoute
  '/premium': typeof PremiumRoute
  '/profile': typeof ProfileRoute
  '/programacion': typeof ProgramacionRoute
  '/projects': typeof ProjectsRoute
  '/roblox': typeof RobloxRoute
  '/software': typeof SoftwareRoute
  '/staff': typeof StaffRoute
  '/tecnologia': typeof TecnologiaRoute
  '/u/$username': typeof UUsernameRoute
  '/tema/$category/$slug': typeof TemaCategorySlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/ai': typeof AiRoute
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRoute
  '/electricidad': typeof ElectricidadRoute
  '/gamedev': typeof GamedevRoute
  '/hardware': typeof HardwareRoute
  '/help': typeof HelpRoute
  '/notifications': typeof NotificationsRoute
  '/premium': typeof PremiumRoute
  '/profile': typeof ProfileRoute
  '/programacion': typeof ProgramacionRoute
  '/projects': typeof ProjectsRoute
  '/roblox': typeof RobloxRoute
  '/software': typeof SoftwareRoute
  '/staff': typeof StaffRoute
  '/tecnologia': typeof TecnologiaRoute
  '/u/$username': typeof UUsernameRoute
  '/tema/$category/$slug': typeof TemaCategorySlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/ai'
    | '/auth'
    | '/community'
    | '/electricidad'
    | '/gamedev'
    | '/hardware'
    | '/help'
    | '/notifications'
    | '/premium'
    | '/profile'
    | '/programacion'
    | '/projects'
    | '/roblox'
    | '/software'
    | '/staff'
    | '/tecnologia'
    | '/u/$username'
    | '/tema/$category/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/ai'
    | '/auth'
    | '/community'
    | '/electricidad'
    | '/gamedev'
    | '/hardware'
    | '/help'
    | '/notifications'
    | '/premium'
    | '/profile'
    | '/programacion'
    | '/projects'
    | '/roblox'
    | '/software'
    | '/staff'
    | '/tecnologia'
    | '/u/$username'
    | '/tema/$category/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/ai'
    | '/auth'
    | '/community'
    | '/electricidad'
    | '/gamedev'
    | '/hardware'
    | '/help'
    | '/notifications'
    | '/premium'
    | '/profile'
    | '/programacion'
    | '/projects'
    | '/roblox'
    | '/software'
    | '/staff'
    | '/tecnologia'
    | '/u/$username'
    | '/tema/$category/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AiRoute: typeof AiRoute
  AuthRoute: typeof AuthRoute
  CommunityRoute: typeof CommunityRoute
  ElectricidadRoute: typeof ElectricidadRoute
  GamedevRoute: typeof GamedevRoute
  HardwareRoute: typeof HardwareRoute
  HelpRoute: typeof HelpRoute
  NotificationsRoute: typeof NotificationsRoute
  PremiumRoute: typeof PremiumRoute
  ProfileRoute: typeof ProfileRoute
  ProgramacionRoute: typeof ProgramacionRoute
  ProjectsRoute: typeof ProjectsRoute
  RobloxRoute: typeof RobloxRoute
  SoftwareRoute: typeof SoftwareRoute
  StaffRoute: typeof StaffRoute
  TecnologiaRoute: typeof TecnologiaRoute
  UUsernameRoute: typeof UUsernameRoute
  TemaCategorySlugRoute: typeof TemaCategorySlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tecnologia': {
      id: '/tecnologia'
      path: '/tecnologia'
      fullPath: '/tecnologia'
      preLoaderRoute: typeof TecnologiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/software': {
      id: '/software'
      path: '/software'
      fullPath: '/software'
      preLoaderRoute: typeof SoftwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roblox': {
      id: '/roblox'
      path: '/roblox'
      fullPath: '/roblox'
      preLoaderRoute: typeof RobloxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programacion': {
      id: '/programacion'
      path: '/programacion'
      fullPath: '/programacion'
      preLoaderRoute: typeof ProgramacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hardware': {
      id: '/hardware'
      path: '/hardware'
      fullPath: '/hardware'
      preLoaderRoute: typeof HardwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gamedev': {
      id: '/gamedev'
      path: '/gamedev'
      fullPath: '/gamedev'
      preLoaderRoute: typeof GamedevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/electricidad': {
      id: '/electricidad'
      path: '/electricidad'
      fullPath: '/electricidad'
      preLoaderRoute: typeof ElectricidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tema/$category/$slug': {
      id: '/tema/$category/$slug'
      path: '/tema/$category/$slug'
      fullPath: '/tema/$category/$slug'
      preLoaderRoute: typeof TemaCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AiRoute: AiRoute,
  AuthRoute: AuthRoute,
  CommunityRoute: CommunityRoute,
  ElectricidadRoute: ElectricidadRoute,
  GamedevRoute: GamedevRoute,
  HardwareRoute: HardwareRoute,
  HelpRoute: HelpRoute,
  NotificationsRoute: NotificationsRoute,
  PremiumRoute: PremiumRoute,
  ProfileRoute: ProfileRoute,
  ProgramacionRoute: ProgramacionRoute,
  ProjectsRoute: ProjectsRoute,
  RobloxRoute: RobloxRoute,
  SoftwareRoute: SoftwareRoute,
  StaffRoute: StaffRoute,
  TecnologiaRoute: TecnologiaRoute,
  UUsernameRoute: UUsernameRoute,
  TemaCategorySlugRoute: TemaCategorySlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
